# Generated by Django 2.2 on 2021-12-30 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20211230_1835'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='itemsI',
            new_name='items',
        ),
    ]
